<?php /** @var Magento\Framework\View\Element\Template $block */
/** @var Hyva\Theme\ViewModel\Escaper $escaper */ ?>
<?php $viewModel = $block->getData('view_model'); ?>
<script type="text/javascript" id="klvHyvaRecs">
    const klRecsLibJS = document.createElement('script');
    klRecsLibJS.type = 'text/javascript';
    klRecsLibJS.defer = true;
    <?php if ($viewModel->isUseSelfHostedApproach()): ?>
    klRecsLibJS.src = '<?= $escaper->escapeJs($block->getViewFileUrl('Klevu_HyvaPage::js/klevu-recs.js')) ?>';
    <?php else: ?>
    klRecsLibJS.src = 'https://js.klevu.com/recs/v2/klevu-recs.js';
    <?php endif; ?>
    //USED THE UserInteractionEvent Listener
    /**
     * Ref. https://docs.hyva.io/hyva-themes/writing-code/patterns/loading-external-javascript.html#example-deferring-scripts-until-a-specific-user-interaction
     */
    window.addEventListener('init-external-scripts', () => {
        document.head.appendChild(klRecsLibJS);
    }, {once: true, passive: true});
</script>
