<?php
/** @var Klevu\FrontendJs\Block\Html\Head\JsInit $block */
?>
<script type="text/javascript" id="klevu_jsinteractive_hyva">
    window._klvWebhook = window._klvWebhook || [];
    window._klvWebhook.push({
        object: "core",
        scope: "all",
        name: "framework",
        action: "init",
        fire: function () {
            klevu.support.hook(["search"], function () {
                var options = <?php /** @noEscape */ echo $block->getInteractiveOptionsSerialized(); ?>;
                <?php /** @noEscape */ echo $block->getChildHtml('additional_before'); ?>
                klevu(options);
                <?php /** @noEscape */ echo $block->getChildHtml('additional_after'); ?>
            });
        }
    });
</script>
