<?php /** @var Magento\Framework\View\Element\Template $block */
/** @var Hyva\Theme\ViewModel\Escaper $escaper */ ?>
<?php $viewModel = $block->getData('view_model'); ?>

<script type="text/javascript">
    const klLandingPageJS = document.createElement('script');
    klLandingPageJS.type = 'text/javascript';
    klLandingPageJS.defer = true;
    <?php if ($viewModel->isUseSelfHostedApproach()): ?>
    klLandingPageJS.src = '<?= $escaper->escapeJs($block->getViewFileUrl('Klevu_HyvaPage::js/landing-page-theme.js')) ?>';
    <?php else: ?>
    klLandingPageJS.src = 'https://js.klevu.com/theme/default/v2/landing-page-theme.js';
    <?php endif; ?>
    document.head.appendChild(klLandingPageJS);
</script>

<div class="klevuLanding"></div>
