<?php /** @var Magento\Framework\View\Element\Template $block */
/** @var Hyva\Theme\ViewModel\Escaper $escaper */ ?>
<?php $viewModel = $block->getData('view_model'); ?>

<script type="text/javascript" id="kl_cat_nav">
    const klCategoryPageJS = document.createElement('script');
    <?php if ($viewModel->isUseSelfHostedApproach()): ?>
    klCategoryPageJS.src = '<?= $escaper->escapeJs($block->getViewFileUrl('Klevu_HyvaPage::js/catnav-theme.js')) ?>';
    <?php else: ?>
    klCategoryPageJS.src = 'https://js.klevu.com/theme/default/v2/catnav-theme.js';
    <?php endif; ?>
    klCategoryPageJS.type = 'text/javascript';
    klCategoryPageJS.defer = true;
    document.head.appendChild(klCategoryPageJS);
</script>

<div class="klevuLanding"></div>
<script type="text/javascript">
    var klevu_pageCategory = '<?php echo $block->escapeJsQuote($block->getFullCategoryPath()); ?>';
    sessionStorage.setItem("klevu_pageCategory", klevu_pageCategory);
</script>
