<?php /** @var Magento\Framework\View\Element\Template $block */
/** @var Hyva\Theme\ViewModel\Escaper $escaper */ ?>
<?php $viewModel = $block->getData('view_model'); ?>
<?php if ($viewModel->isUseSelfHostedApproach()): ?>
    <script src="<?= $block->getViewFileUrl('Klevu_HyvaPage::js/klevu.js') ?>"></script>
<?php else: ?>
    <script type="text/javascript" src="https://js.klevu.com/core/v2/klevu.js"></script>
<?php endif; ?>
