<?php /** @var Magento\Framework\View\Element\Template $block */
/** @var Hyva\Theme\ViewModel\Escaper $escaper */ ?>
<?php $viewModel = $block->getData('view_model'); ?>

<?php if ($viewModel->isUseSelfHostedApproach()): ?>
    <script type="text/javascript">
        const catnav = document.createElement('script');
        catnav.type = 'text/javascript';
        catnav.defer = true;
        catnav.src = '<?= $escaper->escapeJs($block->getViewFileUrl('Klevu_HyvaPage::js/catnav-theme.js')) ?>';
        document.head.appendChild(catnav);
    </script>
<?php else: ?>
    <script type="text/javascript">
        const catnav = document.createElement('script');
        catnav.type = 'text/javascript';
        catnav.defer = true;
        catnav.src = 'https://js.klevu.com/theme/default/v2/catnav-theme.js';
        document.head.appendChild(catnav);
    </script>
<?php endif; ?>

<div class="klevuLanding"></div>
<script type="text/javascript">
    var klevu_pageCategory = '<?php echo $block->escapeJsQuote($block->getFullCategoryPath()); ?>';
    sessionStorage.setItem("klevu_pageCategory", klevu_pageCategory);
</script>
